### ISSUE TITLE
Copiar o XSTools.

### ISSUE THREAD

**Issue by lututui** [OvoKore/OvoKore#1]
Copiar o XSTools não é necessário desde o [PR 425](https://github.com/OpenKore/openkore/pull/425) do OpenKore, unido em 8 Feb 2017. 

https://github.com/OvoKore/OvoKore/blob/88ddcfc24f3f236a09068e77cca854a9981de80a/src/tela/OrdemKore.java#L316

**Comment by OvoKore** [comment]
feito!
