### ISSUE TITLE
08-Nov-16 recvpackets

### ISSUE THREAD

**Issue by lututui** [OvoKore/OvoKore#2]
https://github.com/OvoKore/OvoKore/blob/88ddcfc24f3f236a09068e77cca854a9981de80a/src/tela/OrdemKore.java#L535

Link raw para download, ao invés de embutir o recvpackets: https://raw.githubusercontent.com/OpenKore/openkore/d5f277c0ca17221c92c268c5c4560d3844404ff6/tables/bRO/recvpackets.txt

**Comment by OvoKore** [comment]
feito!
